apiVersion: apps/v1
kind: Deployment
metadata:
  name: project04-deployment
  labels:
    app: project04
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project04
  template:
    metadata:
      labels:
        app: project04
    spec:
      containers:
      - name: project04
        image: tabbu93/project04:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: project04-service
spec:
  type: LoadBalancer
  selector:
    app: project04
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
